import { Inter } from 'next/font/google'
import './globals.css'

//Componenets
import Header from './components/header'
import Footer from './components/footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Danis hairfashion',
  description: 'Generated by the greatest programmer ever',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
